on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]
  merge_group:

name: binaries

jobs:
  # release binaries
  release-bins:
    runs-on: ${{ matrix.job.os }}
    env:
      BUILD_CMD: cargo
    strategy:
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu,      os: ubuntu-24.04, use-cross: true }
          - { target: armv7-unknown-linux-gnueabihf, os: ubuntu-24.04, use-cross: true }
          - { target: aarch64-unknown-linux-gnu,     os: ubuntu-24.04, use-cross: true }         
        toolchain:
          - stable
        bins:
          - radar
          - 1090

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Populate cache
        uses: ./.github/workflows/cache

      - name: Overwrite build command env variable
        if: matrix.job.use-cross
        shell: bash
        run: |
          echo "BUILD_CMD=cross" >> $GITHUB_ENV
          RUSTFLAGS="-C target-feature=-crt-static" cargo install cross --git https://github.com/cross-rs/cross

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.job.target }}
      - run: $BUILD_CMD +${{ matrix.toolchain }} build ${{ matrix.features }} --target ${{ matrix.job.target }} --release --locked --workspace

      - name: archive
        run: |
          tar -czvf ${{ matrix.bins }}-${{ matrix.job.target }}.tar.gz \
              -C target/${{ matrix.job.target }}/release/ ${{ matrix.bins }}

      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        with:
          name: ${{ matrix.bins }}-${{ matrix.job.target }}.tar.gz
          path: ${{ matrix.bins }}-${{ matrix.job.target }}.tar.gz

      - name: Upload binary to release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df # v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.bins }}-${{ matrix.job.target }}.tar.gz
          asset_name: ${{ matrix.bins }}-${{ matrix.job.target }}.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
