on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:

name: doc

jobs:
  build-doc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Populate cache
        uses: ./.github/workflows/cache

      - uses: dtolnay/rust-toolchain@d76c2a93c593483c9892fd8d2538734f73ed8588 # stable
      - uses: Swatinem/rust-cache@3cf7f8cc28d1b4e7d01e3783be10a97d55d483c8 # v2.7.1

      - name: Check documentation
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --locked --no-deps --document-private-items --all-features
