on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  merge_group:

name: ensure_no_std

jobs:
  build-no-std:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Populate cache
        uses: ./.github/workflows/cache

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          target: thumbv7em-none-eabihf
      - run: cargo build --manifest-path ensure_no_std/Cargo.toml
